### ISSUE TITLE
DataView isn't optimized enough yet

### ISSUE THREAD

**Issue by pocesar** [dcodeIO/ByteBuffer.js#16]
DataView aren't very good right now in raw `op/s`, it seems they haven't been optimized enough yet for production use. Two cases where it performs much slower than bitwise operators:

https://github.com/dominictarr/sha.js/commit/91649a61d6fe8ab2b1f785c1833efa89feeff3b0#commitcomment-4964325

https://github.com/feross/buffer/issues/8#issuecomment-31416797

Maybe in the future when this part of ECMAScript is optimized in the browsers (like `asm.js` is heading to), it could be implemented again.

**Comment by englercj** [comment]
Just a followup on this, I have a project whos other requirements put me into a position where I know typed arrays will exist, meaning there is nothing wrong with using them instead of DataViews (and performance is important).

I see there is a ByteBufferTA.js in the source, but I don't see it in the output. How can I choose to use that flavor of ByteBuffer for browsers?

**Comment by dcodeIO** [comment]
I started working on ByteBufferTA a while ago for this exact purpose, but it isn't finished yet.

**Comment by dcodeIO** [comment]
Just completed ByteBufferTA I believe. There will probably still be some bugs or edge cases, but if you'd like to give it a try: https://github.com/dcodeIO/ByteBuffer.js/tree/master/dist/experimental

**Comment by dcodeIO** [comment]
Just checked: Also passes the ProtoBuf.js test suite.

**Comment by dcodeIO** [comment]
Going to make ByteBufferTA the new ByteBufferAB from 4.0.0 on. The previous ByteBufferAB has been renamed to ByteBufferAB_DataView. See: https://github.com/dcodeIO/ByteBuffer.js/tree/master/dist

**Comment by englercj** [comment]
Awesome! Thanks for this @dcodeIO, really appreciate you being so responsive to issues.

**Comment by englercj** [comment]
As of v4 this can be closed. Thanks for all the hard work @dcodeIO!
