### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by jpacora** [dcodeIO/ByteBuffer.js#41]
Hello, im having this error:
RangeError: Illegal range: 0 <= 21 <= 16 <= 32

My code is:
  var cmd = 'DYD,000000#';
  var command = new ByteBuffer();
  command.writeByte(0x78);
  command.writeByte(0x78); // size
  command.writeByte(5 + cmd.length); // size
  command.writeByte(0x80); //Protocol Number
  command.writeByte(4 + cmd.length); //Length of Command
  command.writeByte(0x91); // Server Flag Bit end
  command.writeUTF8String(cmd)
  command.writeShort(crc.crc16ccitt(command.slice(2, 4)));
  command.writeByte(0x0D); command.writeByte(0x0A); // ending
  console.dir(command)
  socket.write(command.toString('hex'))

**Comment by dcodeIO** [comment]
Looks like you are missing a call to `ByteBuffer#flip()` after all relative write operations are complete.
