### ISSUE TITLE
length property or method to ByteBuffer objects

### ISSUE THREAD

**Issue by murgatroid99** [dcodeIO/ByteBuffer.js#42]
Currently, the only way to check the length of a ByteBuffer object is to subtract `offset` from `limit`. This is somewhat unwieldy, so it would be helpful to have a `length` property or method that calculates that.

**Comment by dcodeIO** [comment]
There is ByteBuffer#remaining()

**Comment by murgatroid99** [comment]
Ah, I see that now. In my opinion, this API has a couple of ideas conflated together. When reading (or writing, I guess), `offset` is used to indicate the position of the read cursor. But when taking a slice, `limit` and `offset` are used as bounds of a view into the Buffer, which doesn't seem to me like something that should change when I subsequently read from a buffer.

**Comment by dcodeIO** [comment]
This is just like other ByteBuffers do it. The idea here is to always use offset as the marker of relative read/write operations, and to call `ByteBuffer#flip()` once all relative operations are complete, which adjusts offset and limit accordingly (to the bounds of our contents of interest).

Closing this for now. Feel free to reopen the issue if necessary.
