### ISSUE TITLE
Question about Signed Variable Length Integers

### ISSUE THREAD

**Issue by jcalfee** [dcodeIO/ByteBuffer.js#44]
I believe I need to encode signed variable length integers.  I'm not very clear on this because I have only one example to work with (a small number).  This may be enough.   I found the following work-around and was able to get proper encoding:

        n=0x16
        n=(n << 1) ^ (n >> 31)
        b = new ByteBuffer(DEFAULT_CAPACITY=4, ByteBuffer.LITTLE_ENDIAN)
        b.writeVarint32(n)

This code encodes 0x16 to 0x2C.  This is consistent with the C++ implementation I'm looking at and consistent with the Signed Integers section at here:  https://developers.google.com/protocol-buffers/docs/encoding#varints

I'm am not sure how to decode it.  Here is more information about the case that came up and a jsfiddle that may help: http://stackoverflow.com/questions/28351493/unexpected-result-in-bytebuffer-js-when-writing-a-variable-integer

**Comment by dcodeIO** [comment]
Try:

```js
var bb = ByteBuffer.allocate(4, ByteBuffer.LITTLE_ENDIAN);

// Write it:
bb.writeVarint32(0x16);

// Ready up the buffer for a new sequence of relative operations
bb.flip();

// Read it
console.log(bb.readVarint32());
```

**Comment by jcalfee** [comment]
I see it now "ZigZag encoding maps signed integers to unsigned integers" .. I knew I picked the right library.  Great, thank you!
