### ISSUE TITLE
Create from Buffer

### ISSUE THREAD

**Issue by englercj** [dcodeIO/ByteBuffer.js#48]
Is there a way to create a byte buffer from an existing buffer (node Buffer or ArrayBuffer).

I am using the `ws` module which when it gets a message in node will be a `Buffer` and in browser will be an `ArrayBuffer`. I would like to create a ByteBuffer using that already existing buffer as the backing store:

```js
var WS = require('ws');

var ws = new WS(...);

ws.binaryType = 'arraybuffer'; // node buffer on node, arraybuffer on browsers

ws.addEventListener('message', function (event) {
    // here, event.data is node buffer or an arraybuffer
    // it would be nice to just create a bytebuffer from it
    var buffer = new ByteBuffer(event.data);
    // or
    var buffer = ByteBuffer.fromBuffer(event.data);
});
```

I looked around briefly but didn't see anything in the API to let me do this (without changing the properties manually). Ideally it would never create a Buffer/ArrayBuffer object because I am giving it one instead.

Right now I am doing this as a workaround:

```js
var bb = new ByteBuffer(0);
bb.buffer = event.data;
// TODO: I would rather use a typed array here for the view, see:
// https://github.com/dcodeIO/ByteBuffer.js/issues/16#issuecomment-110802403
bb.view = process.browser ? new DataView(event.data) : null;
bb.limit = process.browser ? event.data.byteLength : event.data.length;
```

**Comment by dcodeIO** [comment]
Yes: `ByteBuffer.wrap(nodeBuffer)`

**Comment by englercj** [comment]
Ah perfect, sorry about that!

**Comment by secwang** [comment]
should add to readme.This is too important.
