### ISSUE TITLE
Don't use instanceof for isByteBuffer

### ISSUE THREAD

**Issue by englercj** [dcodeIO/ByteBuffer.js#52]
Using `instanceof` for the [isByteBuffer](https://github.com/dcodeIO/ByteBuffer.js/blob/master/src/methods/static/isByteBuffer.js#L8) check can break in certain situations.

For example,, I have a lib that uses a specific version of ByteBuffer. Then I have a project that uses a different version of ByteBuffer.

If my lib returns a ByteBuffer, and then I do `ByteBuffer.isByteBuffer(value)` in my project **it will return `false`** because the prototype of the two version is different. This is a problem because you can't guarantee the two prototypes are always the same.

Instead of doing instanceof there should be a duck type check:

```js
function ByteBuffer() {
    this.__isByteBuffer = true;
}

ByteBuffer.isByteBuffer(bb) {
    return (bb && bb.__isByteBuffer);
}
```

**Comment by dcodeIO** [comment]
This adds a non-configurable, non-enumerable property to the prototype and tests for it. Let me know if this does what you need, or whether you require a standard property instead.

**Comment by englercj** [comment]
That is perfect, thanks!
