### ISSUE TITLE
Release 5.0.1?

### ISSUE THREAD

**Issue by chadharrington** [dcodeIO/bytebuffer.js#69]
Thank you for accepting @cemerick 's pull request with the missing bytebuffer.js externs. We use your packages (long.js and bytebuffer.js) in Clojurescript via the cljsjs packages repository (https://github.com/cljsjs/packages). We'd like to include the updated bytebuffer.js package, but we need a released version to do that. Would you mind releasing a version 5.0.1 of bytebuffer.js with the missing externs commit included? That would allow the entire Clojurescript ecosystem to use your package easily.

Thanks for your great work on this and many other projects.

**Comment by dcodeIO** [comment]
It's on npm now!

**Comment by chadharrington** [comment]
Wow. That was fast! Thanks for your help.
