### ISSUE TITLE
Convert ByteBuffer instance into Uint8Array?

### ISSUE THREAD

**Issue by niftylettuce** [dcodeIO/bytebuffer.js#70]
Here's what I currently do to convert it - I was curious if there was a helper method for this?

```js
          let val = ByteBuffer.atob(data.value);
          let bytes = new Uint8Array(val.length);
          for (let i = 0; i < bytes.length; i++) {
            bytes[i] = val.charCodeAt(i);
          }
```

**Comment by dcodeIO** [comment]
There is `ByteBuffer#toArrayBuffer`:
```js
let bytes = new Uint8Array(ByteBuffer.atob(data.value).toArraybuffer())
```

**Comment by niftylettuce** [comment]
@dcodeIO Thx for this, btw you might want to edit your code snippet you mentioned to fix typo:

```diff
+.toArrayBuffer()
-.toArraybuffer()
```

**Comment by niftylettuce** [comment]
Actually, the function does not exist.  The following throws an error:

```js
          let bytes = new Uint8Array(
            ByteBuffer.atob(data.value).toArrayBuffer()
          );
```

`_bytebuffer2.default.atob(...)toArrayBuffer is not a function`

**Comment by niftylettuce** [comment]
Instead, the suggested answer should be `fromBase64` instead of `atob`, as `atob` does not return a `ByteBuffer` instance?

```js
          let bytes = new Uint8Array(
            ByteBuffer.fromBase64(data.value).toArrayBuffer()
          );
```

**Comment by dcodeIO** [comment]
You are right, I edited my answer accordingly.

**Comment by niftylettuce** [comment]
@dcodeIO Just wanted to say this repo is badass, thanks so much for making it.
