### ISSUE TITLE
writeBytes is undefined

### ISSUE THREAD

**Issue by evanw** [dcodeIO/bytebuffer.js#74]
I see `ByteBufferPrototype.writeBytes = ByteBufferPrototype.append;` and then later on `ByteBufferPrototype.append = function(source, encoding, offset) {`. The order of these should be switched otherwise `writeBytes` will be undefined.

**Comment by XuJinNet** [comment]
+1
version: 5.0.1

**Comment by Carnewal** [comment]
+1
