### ISSUE TITLE
How to deserialize?

### ISSUE THREAD

**Issue by gilly3** [dcodeIO/bytebuffer.js#75]
I've got a serialized bytebuffer by calling `.toRaw()` on a protobuf.js message.  What's the best way to deserialize that?  I don't see, for example, `ByteBuffer.fromRaw()`, or anything like that.

**Comment by dcodeIO** [comment]
`ProtoBuf.Builder.Message#toRaw` from protobuf.js just converts the message object to a plain JS object. For encoding, see `Message#encode`. A ByteBuffer is just a wrapper around a byte array.

**Comment by gilly3** [comment]
My message contains binary data.  Eg, something like this (vastly oversimplified):

```
message foo {
    optional string id = 1;
    optional int count = 2;
    optional string comment = 3;
    optional bytes data = 4;
}
```

I receive and decode a protocol buffer, then call `var plainObj = decoded.toRaw();`.  Later, I want to read the binary data contained in `plainObj.data`.  Is there a method that converts the plain js object representing `optional bytes data = 4;` back into a buffer?

For now, I'm changing the value to a base64 string via `decoded.data = decoded.data.toBase64()` before calling `decoded.toRaw()`, then I'm using `ByteBuffer.fromBase64(plainObj.data)` to get the buffer.  This works, but if there's a way to get the buffer from the plain object, that seems like it would be preferable.

**Comment by dcodeIO** [comment]
Well, `decoded.data` holds the contents you are interested in already, between its `offset` and `limit` property. Actually `ByteBuffer.fromBase64(decoded.data.toBase64())` just copies it through converting it to base64 and back.

To get the raw ArrayBuffer or Buffer from `decoded.data`, use `decoded.data.toBuffer/toArrayBuffer()` respectively.

**Comment by gilly3** [comment]
Thanks
