### ISSUE TITLE
Uncaught TypeError: buf.readUint64 is not a function 

### ISSUE THREAD

**Issue by havenspool** [dcodeIO/bytebuffer.js#82]
Uncaught TypeError: buf.readLong is not a function 
and more

**Comment by dcodeIO** [comment]
Int64 support [requires](https://github.com/dcodeIO/bytebuffer.js/blob/master/src/types/ints/int64.js#L4) [long.js](https://github.com/dcodeIO/long.js) to be present.

**Comment by havenspool** [comment]
All right, thank you!
