### ISSUE TITLE
easy way to read a bunch of characters at current offset?

### ISSUE THREAD

**Issue by pocesar** [dcodeIO/ByteBuffer.js#9]
I'm struggling to make it read an array of bytes after a couple of readInt8/16's, `printDebug` is showing the right offset, but I'm failing to retrieve only 7 bytes from the array. tried using copy, slice (it's returning the whole array), clone, along with mark, flip, compact.

**Comment by seishun** [comment]
I would be useful to have a method that returns a slice of the specified length from the current offset and advances the offset accordingly. Currently, it has to be done in two calls:

```js
var slice = myByteBuffer.slice(myByteBuffer.offset, myByteBuffer.offset + sliceLength);
myByteBuffer.skip(sliceLength);
```

How about having this instead?

```js
var slice = myByteBuffer.readBytes(sliceLength);
```
